import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { classNames } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="light">
            <body
                className={classNames(
                    'min-h-screen font-sans antialiased grainy',
                    inter.className
                )}
            >
                {children}
            </body>
        </html>
    )
}
